services:
  fastapi:
    build: .
    container_name: fastapi_book_project_afanyu
    # Remove the ports mapping here! (don't expose FastAPI directly)
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8213:8213" # Map host port 8213 to Nginx container port 8213
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Ensure the config is mounted
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
