services:
  fastapi:
    build: .
    container_name: fastapi_book_project_afanyu
    ports:
      - "8213:8213"
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx:/etc/nginx:ro
    depends_on:
      - fastapi
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
