name: deploy 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Stop and remove existing containers
            cd /home/afa/projects/fastapi-book-project
            docker-compose down

            # Pull latest code
            git pull origin main

            # Rebuild and restart Docker containers
            docker-compose up -d --build

            # Restart related services
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart nginx
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl daemon-reload
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S systemctl restart fastapi_book_project

            # Verify service status
            docker ps
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo systemctl status fastapi_book_project
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo systemctl status nginx
